# Makefile for GNU Make.
# $Id: GNUmakefile,v 1.2 2004/09/15 21:46:24 vhex Exp $

include ../Makedefs.faerion.include

TARGET = executable
PROG   = zatp-$(VERSION)
SRCS   = $(wildcard *.cc libfaeutil/*.c)
LIBS  += stdc++

include ../Makedefs.faerion
